name: Docker Actions

on:
  issues:
    types: [opened]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: meow
        uses: ./.github/actions/cat-facts
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: main_artifact
          path: /all/final.zip
