name: Docker Actions

on:
  issues:
    types: [opened]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: meow
        uses: ./.github/actions/cat-facts
